### ISSUE TITLE
Make labels bold again

### ISSUE THREAD

**Issue by Gymnasiast** [daattali/oldschool-github-extension#1]
Thanks for making this extension!

For me, one of the biggest usability problems with the new look of Github is the horribly thin font of labels - for example, those in the issue list (e.g. `bug`, `help wanted`). Same goes for the number of issues and pull requests (a number, displayed in a bubble). I was wondering if you could add CSS to tackle that as well.

**Comment by daattali** [comment]
I just looked at an old issues page using wayback machine and compared to current. I don't see what you mean. Can you post a screenshot?

**Comment by Gymnasiast** [comment]
Certainly. This is what I mean:

![afbeelding](https://user-images.githubusercontent.com/1478678/85585812-a627a680-b640-11ea-8638-b9d7a883b4ad.png)

In above screenshot, the number in the bubble is bold.

It is much thinner now: 
![afbeelding](https://user-images.githubusercontent.com/1478678/85586044-da9b6280-b640-11ea-8b74-2f3526df9af3.png)

The same applied to issue labels:
![afbeelding](https://user-images.githubusercontent.com/1478678/85586466-3f56bd00-b641-11ea-9593-7823ab64d6b7.png)

**Comment by daattali** [comment]
Oh interesting. It doesn't render like that to me, renders identical. You're not on Chrome on Windows I suppose? I'll try to see

**Comment by daattali** [comment]
Yes on Firefox it does render differently. Will do.

**Comment by daattali** [comment]
Fixed with af005463c1b11284c7c1e6992ba4fa569d97cb8a

**Comment by Gymnasiast** [comment]
Thank you! Especially for picking this up so quickly. :+1: 

(I am indeed on Firefox, on Linux. Apparently, Github didn't test their new theme properly in Firefox?)

**Comment by daattali** [comment]
The add on will be updated on firefox within the hour
