### ISSUE TITLE
Mousing away from the file explorer does not remove hover highlight

### ISSUE THREAD

**Issue by karai17** [daattali/oldschool-github-extension#10]
When I mouse over the file explorer, The row that my mouse is over gets highlighted as expected. When I mouse away from the explorer via the top or bottom, the highlight goes away as expected. When I mouse away via the left or right however, the highlight does not go away.

**Comment by karai17** [comment]
This seems to affect all lists including the issues list.

**Comment by daattali** [comment]
I agree that's a bit strange, but it was always like that. You can look at waybackmachine to view old github pages and it's been this way for years.

**Comment by daattali** [comment]
Sorry to close both your issues. Feel free to make more suggestions if you see something that changed its appearance this week
