### ISSUE TITLE
Wider comment forms

### ISSUE THREAD

**Issue by szepeviktor** [daattali/oldschool-github-extension#13]
Thank you for reverting some design updates.

Do you plan to make the comment form smaller again?

**Comment by daattali** [comment]
Was it smaller before? Please show me the difference before and after. I don't recall that being different.

**Comment by szepeviktor** [comment]
Current size

![kép](https://user-images.githubusercontent.com/952007/85827991-aaaaa700-b787-11ea-8ed6-4032e0730b94.png)

**Comment by daattali** [comment]
Was it smaller before? I can see what it looks like now, but I don't have any reference to see if it was smaller before. If you can show me hwo it looked before that would help.

**Comment by szepeviktor** [comment]
You must know the 600px rule. It is the biggest width which can be read easily.

```css
.container-xl {
    max-width: 970px;
}
```

Now the comment form is 600 px :)

![kép](https://user-images.githubusercontent.com/952007/85828314-61a72280-b788-11ea-88c7-fb457a218853.png)

**Comment by szepeviktor** [comment]
Actually it was 700px: https://guides.github.com/features/issues/example-issue.png
But I like 600 better :)

**Comment by daattali** [comment]
If you have away to see exactly what it looked like previously, I can look into it. From that screenshot I can't really gather too much information. For all the other work I've done here, I used waybackmachine to see exactly how things looked

**Comment by szepeviktor** [comment]
> I used waybackmachine to see exactly how things looked

That is wise.

Yes, in the old times the comment form was exactly 700px wide

https://web.archive.org/web/20190512205747/https://github.com/Homebrew/brew/pull/1

**Comment by szepeviktor** [comment]
With the avatar:

```css
.discussion-timeline {
    width: 760px;
}
```

**Comment by daattali** [comment]
That looks like the entire page layout is different, not just the style of one item. As the Limitations section in the README says, I can't reliably change the layout without inadvertedly affecting other pieces of the page. Unfortunately I don't think this will be handled here.

**Comment by szepeviktor** [comment]
Thank you.

Does you extension have options?
Maybe it would be possible to handle this with `disabled` as default.

**Comment by zekefarwell** [comment]
I just put a max-width and margin: auto on the comment column and it looks pretty decent.  It is out of alignment with the overall page width though, so I won't pursue and test this further if @daattali feels it's out of scope for this extension.

<img width="1280" alt="Screen Shot 2020-06-26 at 11 59 11 AM" src="https://user-images.githubusercontent.com/281482/85877069-988b3180-b7a4-11ea-82df-f41a10810abf.png">

...

<img width="1214" alt="Screen Shot 2020-06-26 at 11 58 25 AM" src="https://user-images.githubusercontent.com/281482/85877046-8f9a6000-b7a4-11ea-8a51-ee5626bc88c9.png">

**Comment by daattali** [comment]
@szepeviktor That's a good idea, to introduce options so that you can choose to opt-in/out of certain features!

**Comment by zekefarwell** [comment]
A nice idea, but definitely would increase the maintenance burden

**Comment by daattali** [comment]
I don't like that the entire page's alignment changes, and not for the better, because of this. So I don't think I want to include that as a default.

But if there are opt-in options then it could be added. I opened an issue for that #16

**Comment by szepeviktor** [comment]
Okay.

**Comment by daattali** [comment]
If #16 ends up being implemented (big if), then this issue is already linked there and will be addressed
