### ISSUE TITLE
Can i have a square buttons instead of circles one ;-;

### ISSUE THREAD

**Issue by mkcoldwolf** [daattali/oldschool-github-extension#15]
AS title ;-; , my CSS is too trash to contribute
![image](https://user-images.githubusercontent.com/32544898/85865898-2b55bb80-b7f9-11ea-8704-002ed4a89184.png)
Radius of those button are not that sick on the old school github

**Comment by zekefarwell** [comment]
There were some commits that set the button border radius back to the same as the classic UI.  It had some unintended side effects though so it had to be reverted.  It may be possible to do it in a more targeted way though.

**Comment by daattali** [comment]
@zekefarwell is correct.

There are a lot of buttons and they're used in many contexts in a variety of ways. After setting the button radius,I wasn't trying to look for issues but I accidentally ran into a few issues (there are probably even more if I tried looking for them):
- the "raw"/"blame" button (when viewing a file) are touching each other and their shared section had to be flat and it was rounded 
- same thing was happening to the 3 counters at the top "watch"/"star"/"fork"
- same thing with the "merge"/type of merge button in a PR

The annoying thing is that github didn't think about making these buttons share CSS classes, do they can't be handled nicely generically. You would have to find ALL the buttons in the site and make sure to target each one.

Unfortunately I don't think that's a good idea

**Comment by zekefarwell** [comment]
@mkcoldwolf, a solution for classic, more square buttons was implemented in #22
