### ISSUE TITLE
Border Radius: Old 3px vs New 6px?

### ISSUE THREAD

**Issue by zekefarwell** [daattali/oldschool-github-extension#19]
This extension reverts some elements to the old 3px border radius while leaving lots of others at 6px which makes things look a little inconsistent.  I've made some good progress reverting buttons and other elements to 3px without too many more lines of css, however the more I look at the wayback machine, the more I realize just how many elements were changed from 6px border radius to 3px that will need to be changed for consistent look.

Personally, although I prefer the old 3px radius, I don't absolutely hate the new 6px radius.  The inconsistency of some boxes being reverted to 3px while the rest are 6px does bother me though.  I think this extension should choose either 3px or 6px radius and stick with it.  If the goal is to be as close as possible to classic github with 3px border radius, I will help achieve that with minimal css.  If you want to stick with 6px, I think that's sensible too.

**Comment by daattali** [comment]
The goal is 3. Are there many places that still use 6, except for the buttons? I'd be happy to make the buttons 3 as well, but that would require fixing all the buttons across github, which isn't a small task

**Comment by zekefarwell** [comment]
Cool.  Happy to help with reverting to 3px border radius.  Buttons, labels, form fields, search boxes, avatars, navbars, pagination, and various other boxes are all 6px in the new design and were 3px in the old.  It's definitely a lot of elements, but I think it can be done carefully with css rules that are neither too broad or too specific. 

Here are some screenshots from the wayback machine showing a variety of things with 3px border radius.  I'm sure there are more.  Many items in all the settings pages for example.  Those are hard (impossible?) to see on the wayback machine though.

<img width="567" alt="Screen Shot 2020-06-27 at 1 18 57 PM" src="https://user-images.githubusercontent.com/281482/85928909-b5943300-b87e-11ea-97a8-11d53efe3977.png">
<img width="1055" alt="Screen Shot 2020-06-27 at 1 18 40 PM" src="https://user-images.githubusercontent.com/281482/85928910-b5943300-b87e-11ea-8d9f-b3ebe4baf553.png">
<img width="1035" alt="Screen Shot 2020-06-27 at 1 16 41 PM" src="https://user-images.githubusercontent.com/281482/85928911-b62cc980-b87e-11ea-8a89-ece97bf435c3.png">
<img width="1080" alt="Screen Shot 2020-06-27 at 1 16 25 PM" src="https://user-images.githubusercontent.com/281482/85928912-b62cc980-b87e-11ea-9069-7d4032a11656.png">

I've got some uncommitted changes on my fork that set most of the buttons to 3px without breaking the look of the button groups (split buttons with straight line in between).  I'll submit a PR at some point when it gets to a good place.

**Comment by daattali** [comment]
Sounds good :)

**Comment by daattali** [comment]
I'm closing this issue as you've already addressed most places. The few remaining 6px can be addressed separately
