### ISSUE TITLE
Restore commit message of latest commit

### ISSUE THREAD

**Issue by NoShotz** [daattali/oldschool-github-extension#21]
I find it really annoying that you need to click a button to see the latest commit message on the main page of repositories. It would be really nice if it functioned like it did before.

**Comment by daattali** [comment]
That would indeed be wonderful. There was some discussion on this already, and unfortunately the only way to show the message on page load would have the side effect of not being able to hide the message. I don't think it's possible with only CSS to show the message on page load but still retain the toggle ability.
