### ISSUE TITLE
Chrome Web Store Still Stuck On v1.1

### ISSUE THREAD

**Issue by zekefarwell** [daattali/oldschool-github-extension#24]
Not an issue for me since I've installed the extension directly from the git repo, but I just noticed that the Chrome extension listing here is still on version 1.1.  Not sure how the update process works with the chrome webs store, but figured I'd flag in case you hadn't noticed.
https://chrome.google.com/webstore/detail/old-school-github/blkkkhifjoiedclojflfcenbjigdajeb

**Comment by daattali** [comment]
Yeah I tried submitting 1.2 multiple times and the store was having issues.

I just submitted 1.3, hopefully that will get through.

**Comment by zekefarwell** [comment]
Excellent.  Looks it's updated to 1.3 now.
