### ISSUE TITLE
Change followers and stars user information back to the old layout

### ISSUE THREAD

**Issue by CelestialAmber** [daattali/oldschool-github-extension#27]
This is how the profile page looked before the UI update (link: http://web.archive.org/web/20190110133038/https://github.com/SourMesen):
![image](https://user-images.githubusercontent.com/36093934/86057223-c8e50100-ba2c-11ea-9620-cbc513f64736.png)

This is how it looks now (with the current changes made by the extension):
![image](https://user-images.githubusercontent.com/36093934/86057894-f9796a80-ba2d-11ea-9286-13107cf5e57f.png)

**Comment by CelestialAmber** [comment]
Sorry for first bringing this up in the other pull request.

**Comment by daattali** [comment]
Oh do you mean adding the two tabs on the right side that show the stars and followers? Or is it something else

**Comment by CelestialAmber** [comment]
Yes, that's what I meant.

**Comment by CelestialAmber** [comment]
I guess at the same time, if it's possible it would also be nice to just revert the look of the tabs (including the numbers for the repositories) to the original as much as possible.

**Comment by daattali** [comment]
We cannot add I formation (as tabs), only change the look of existing elements on the page.

Regarding the tabs: same thing. They look like they did before but we can't add new information that's not currently there

**Comment by daattali** [comment]
Sorry for the typos and weird message, I was typing on mobile in a rush!
