### ISSUE TITLE
Disinformation in README

### ISSUE THREAD

**Issue by Kira-NT** [daattali/oldschool-github-extension#29]
> The reason is because of the strange way GitHub handles internal links: some pages are actual page reloads, but some pages are fully loaded with AJAX. This makes it impossible to use JavaScript to fix any UI issues, and only CSS can be used. If you're on the Code tab and you click on Pull Requests then you don't actually refresh the page, but if you click on Issues then it is a new page. What that means is that after moving from Code to Pull Requests, any JavaScript changes are reverted because large portions of the page body were re-written. Technically it's possible to find hacky ways around that, using event listeners or mutator observers or any other technique and try to force a re-initialization of the JavaScript when a new page is AJAX-loaded, but that would be extremely difficult to work correctly and would be non performant. So unfortunately only CSS is used.

Hi there!
Please stop misleading your followers and remove this piece from README

**Comment by Kira-NT** [comment]
@Gymnasiast, what's wrong?

**Comment by daattali** [comment]
I don't know who @Gymnasiast is, but perhaps he did not appreciate your hostile tone ("stop misleading your followers" vs "I don't think this is true, you should consider removing it"). Regardless, I'll consider your request

**Comment by Kira-NT** [comment]
> your hostile tone

Oh, I'm really sorry, didn't mean to hurt anybody! English isn't my native language, so sometimes I may use words that aren't the most suitable for something I want to express...

I just wanted to point out that some statements aren't really true, like:

> impossible to use JavaScript to fix any UI issues
> [...] that would be extremely difficult to work correctly and would be non performant

And I don't "think" so, I simply know it

> @daattali closed this in 7a1ef80 11 hours ago

P.S. - "This makes it impossible to use JavaScript" is still there xD

**Comment by daattali** [comment]
"impossible" is no longer there. I removed it 16 hours ago. I do want to mention this as a non-trivial thing because it **is** more complex than pure CSS or than simple straight forward javascript.

**Comment by Kira-NT** [comment]
> "impossible" is no longer there. I removed it 16 hours ago

Whoops, yeah. Missed 23bf1c8717f0d2f312657dfb8e55439939c3c06c

> this as a non-trivial thing because it **is** more complex than pure CSS or than simple straight forward javascript

Absolutely true, nothing to argue about

I apologize for being so annoying, but I have my own reasons :)
Actually, I made that "impossible" solution, and everything would be great if some very "smart" people wouldn't begin to prove to me that my script **won't** work, because it's **said** so in the README of the more famous repository... It becomes somehow insulting that people disrespect your creation, while they didn't even try to use it ¯\\_(ツ)_/¯

Well, thank you much for cooperation! You saved me from a further influx of people who don't want to think with their own heads :)

**Comment by daattali** [comment]
I have a few dozen open source packages much much much bigger than this one, so I'm very familiar with people questioning everything about a topic I spent 3 years building. It is indeed frustrating.
