### ISSUE TITLE
Add a user style version

### ISSUE THREAD

**Issue by kidonng** [daattali/oldschool-github-extension#30]
Since this is a CSS only solution, I suggest adding a user style version so people like me who don't want to install lots of extensions can use it with a user style manager (like [Stylus](https://github.com/openstyles/stylus)) instead.

There should be a GitHub action to generate an `oldschool-github.user.css` when the style is updated:

```css
/* ==UserStyle==
@name         Old School GitHub
@version      <insert version>
@description  Reverts most of GitHub to its classic look
@license      MIT
@author       daattali
@homepageURL  https://github.com/daattali/oldschool-github-extension
@namespace    daattali
==/UserStyle== */

@-moz-document url-prefix("https://github.com/"), url-prefix("https://gist.github.com/") {
  <insert style>
}
```

**Comment by daattali** [comment]
Thanks for the suggestion. I've never written a user style I'm not at a place where I can devote time to learn that right now, so any help is appreciated.

**Comment by kidonng** [comment]
I will try to submit a PR then ❤

**Comment by zekefarwell** [comment]
You could just copy and paste the css into Stylus.  That's how I started using it in Firefox before @daattali submitted it as a Firefox addon.

**Comment by kidonng** [comment]
Sure, but what about updates? So I'm creating an automated solution for this.
