### ISSUE TITLE
When both Old School Github and Refined Github are installed, top bar is too far to the right

### ISSUE THREAD

**Issue by nyanpasu64** [daattali/oldschool-github-extension#32]
If you install both Old School Github and Refined Github, both extensions attempt to center the top bar. As a result, it's too far to the right.

![image](https://user-images.githubusercontent.com/913957/87630998-55f5ae80-c6eb-11ea-9836-6331780b6432.png)

Refined Github has a large number of options, but even with all options unchecked, this issue persists.

**Comment by daattali** [comment]
I'm surprised that's the only issue that comes up :) Both extensions make extensive UI changes so there should definitely be some clashes. I can only make changes assuming the real github site as the base, I cannot make the changes work alongside other independent extensions.
