### ISSUE TITLE
The feature "Move header tabs to main content area" stopped working today

### ISSUE THREAD

**Issue by ghost** [daattali/oldschool-github-extension#33]
This extension used to center the header tabs on large monitors, but earlier today (after GitHub made some more changes, I assume), I noticed that these tabs are on the left side of the screen again. The extension's other features still seem to be working fine (see screenshots).

**Oldschool GitHub turned off**
![off](https://xbb.datahoarder.dev/VUSu3/JIZeCIGa43.png/raw)

**Oldschool GitHub turned on**
![on](https://xbb.datahoarder.dev/VUSu3/vIfACUYE63.png/raw)

**Comment by daattali** [comment]
Thanks for letting me know. I tried pushing a quick fix, let me know if it's better now (it's not on the chrome store yet, you'll have to install it manually)

**Comment by daattali** [comment]
Let me know if it works for you, and I'll then submit it to the stores

**Comment by ghost** [comment]
@daattali Thanks for the quick fix! I can confirm that be803fb resolves the issue for me.

![new](https://xbb.datahoarder.dev/VUSu3/gIvASofE37.png/raw)
