### ISSUE TITLE
Long profile statuses are cropped

### ISSUE THREAD

**Issue by cl0ne** [daattali/oldschool-github-extension#34]
Actual result:
![status_1](https://user-images.githubusercontent.com/271097/87945104-f3186480-caa8-11ea-98b5-8e15ba84d10b.png)

Expected something like this (I've just disabled `nowrap` class for status container):
![status_2](https://user-images.githubusercontent.com/271097/87945097-f0b60a80-caa8-11ea-8829-7e9937c27ff3.png)

Original look without styles:
![status_no_css](https://user-images.githubusercontent.com/271097/87945093-edbb1a00-caa8-11ea-8d9d-331f9882d511.png)

**Comment by daattali** [comment]
Can you please check with the newest version and confirm it's fixed? You'll have to test it by manually importing the extension, I'l only submit it to the extension store after your confirmation

**Comment by cl0ne** [comment]
> Can you please check with the newest version and confirm it's fixed? You'll have to test it by manually importing the extension, I'l only submit it to the extension store after your confirmation

I don't use extension, I use css directly as userstyle (for some time I kept them as a [gist](https://gist.github.com/cl0ne/04b4446fae883a1f036db4b3dabc9496), later I switched to userstyle from your repo).

Can confirm that the issue is fixed now, thanks.
![fixed](https://user-images.githubusercontent.com/271097/87970496-82833f00-cacc-11ea-8663-3200ea90afca.png)

**Comment by daattali** [comment]
Will submit
