### ISSUE TITLE
Expose this as a userscript so it can be used with Tampermonkey/Greasemonkey

### ISSUE THREAD

**Issue by dumptyd** [daattali/oldschool-github-extension#35]
I use Tampermonkey for my site customization needs. It would be nice if this was provided as a userscript as well so I could just use the extension that I already have instead of installing a userstyle manager.

**Comment by daattali** [comment]
It is offered as a user script as well. Check out the top section of the README, the user script is in the css folder

**Comment by dumptyd** [comment]
Maybe I'm looking in the wrong place but here https://github.com/daattali/oldschool-github-extension/tree/master/css I only see a user style and those can't be used with userscript managers.

**Comment by daattali** [comment]
Oh a  user style and a user script are not the same thing? I'm not familiar with user scripts as I never used one, I'd be happy for a PR to create that in the same way the user style is generated
