### ISSUE TITLE
Is this not implemented or on purpose?

### ISSUE THREAD

**Issue by TheTechRobo** [daattali/oldschool-github-extension#38]
Noticed a very minor detail: when I hover over e.g. Pull requests tab it shows the grey bar under it like in the new version:

![Screenshot 2020-09-18 at 18 55 25](https://user-images.githubusercontent.com/52163910/93651789-be5d5680-f9e0-11ea-8320-d11935f9ef6b.png)

Is this fix just not implemented, or is it on purpose? 

(If it's just not implemented, I'd suggest bolding the button text on hover like the old one did to make sure it looks clickable.)

**Comment by daattali** [comment]
Are you sure it used to bold?

I just looked at a repository snapshot from May 2019 and it loooks like there was no hover effect https://web.archive.org/web/20190512205747/https://github.com/Homebrew/brew/pull/1

I'm ok with keeping the new hover effect of a grey underline, I do think it's an improvement over no hover effect at all

**Comment by TheTechRobo** [comment]
Huh weird, I could have sworn there was a hover effect. :thinking:

**Comment by TheTechRobo** [comment]
Oops, asccidentally closed

**Comment by TheTechRobo** [comment]
Do you have any idea for custom CSS for a hover effect?

**Comment by daattali** [comment]
I think the current is good. Common effects for hover are bolding/changing font colour/changing background colour. If there was no hover effect previously, then I won't be explicitly adding one

**Comment by TheTechRobo** [comment]
Sounds good.
