### ISSUE TITLE
Tabs are no longer centred

### ISSUE THREAD

**Issue by Montandalar** [daattali/oldschool-github-extension#41]
Hi, I use the user style sheet with Stylus on Firefox. GitHub may have changed its CSS or HTML, because for me now the tabs at the top of a repository - "Code", "Issues", etc, have gone back to GitHub's new left-alignment style.
![image](https://user-images.githubusercontent.com/13659694/110437656-b8337180-8109-11eb-8b71-80a6d804cbb7.png)

**Comment by zekefarwell** [comment]
Yeah github changed something a couple of weeks ago.  previously reported in #40
