### ISSUE TITLE
The "parent folder" (`..`) in file list has too much whitespace 

### ISSUE THREAD

**Issue by daattali** [daattali/oldschool-github-extension#6]
![image](https://user-images.githubusercontent.com/952340/85756100-834ad000-b6dc-11ea-939a-e40eb3a84a8e.png)

**Comment by zekefarwell** [comment]
Agreed.  Just looked [on the wayback machine](https://web.archive.org/web/20190322012401/https://github.com/django/django/tree/master/django) (have to turn off JS or the new design gets pulled in after page load!) and the "parent folder" row is the exact same height as the other rows.

<img width="502" alt="Screen Shot 2020-06-25 at 12 48 59 PM" src="https://user-images.githubusercontent.com/281482/85763504-b55f3080-b6e2-11ea-8e40-8185be696c7e.png">
