### ISSUE TITLE
Match All Github URLs Instead of Excluding User Profile and Org Pages?

### ISSUE THREAD

**Issue by zekefarwell** [daattali/oldschool-github-extension#8]
I was still seeing round user avatars on profile pages even though the css exists to revert them to 6px border radius.  Turns out the reason is because in the `manifest.json`, the extension matches `https://github.com/*/*`.  Profile pages (and organization pages) don't follow this pattern.  Their urls are just `github.com/username` so the extension needs to match `https://github.com/*` to affect them.  

So that's a simple change that could be made, but after comparing user pages on the wayback machine, I'm not sure if it's a wanted change or not.  

**User page in 2019:**
<img width="1038" alt="Screen Shot 2020-06-25 at 1 56 26 PM" src="https://user-images.githubusercontent.com/281482/85773451-da0bd600-b6eb-11ea-908a-4d00c9aa51c4.png">

**User page today:**
<img width="1272" alt="Screen Shot 2020-06-25 at 1 56 35 PM" src="https://user-images.githubusercontent.com/281482/85773489-e5f79800-b6eb-11ea-9134-dfae7d2b1b87.png">

**User page with old-school-github active:**
<img width="1247" alt="Screen Shot 2020-06-25 at 2 02 35 PM" src="https://user-images.githubusercontent.com/281482/85774280-aed5b680-b6ec-11ea-8b55-2f67bdacf20d.png">
** You can see this yourself by typing a slash after the username in the url -  https://github.com/fabpot/ instead of https://github.com/fabpot.  obviously we'd want to remove that line under the active tab.

The screenshots show that the new style tabs were already on the user profile page last year.  So should this extension change the tabs on the profile page to the old style that was used everywhere else, or not?  It is the classic style and fits better with the rest of the github.  But if the goal of the extension is just to make github look like it did before 6/23/2020, then changing those tabs is overstepping 😀🤔.  

Thoughts?

**Comment by daattali** [comment]
I like your way of adding the `/` to see it using the new style :)

I did notice this page, I explicitly wanted the new style on repo pages and not on profile pages because it seemed to have a few other unintended consequences here (the ones you mention: the status smiley is now on top of the picture, and the tabs don't look like they did before)

I actually don't have a 100% opinion on whether the new style should or should not exist on profile pages. I chose to exclude it, but I'm open to changing my mind if you really think otherwise?

An interesting point I just noticed: organization avatar photos are not rounded , only user avatar photos!

**Comment by zekefarwell** [comment]
Yeah I was only looking into it because I this extension changes the avatar photos from round to squares with round corners everywhere except on the profile page.  So I just just trying to change that.  Definitely some more work would be needed to make the extension play nicely with the profile page.

I think it would ultimately be nice for the extension to affect all pages.  It's a bit jarring to have the ui look just slightly different on the home page, org pages, and user profile pages (maybe other too?)  I was just at the home page and saw the bad looking flat style on the New button 🙁
<img width="453" alt="Screen Shot 2020-06-25 at 2 21 41 PM" src="https://user-images.githubusercontent.com/281482/85777057-463c0900-b6ef-11ea-88ad-0a93ffd5e5fe.png">

**Comment by daattali** [comment]
What do you propose to do with the tabs on those pages?

**Comment by daattali** [comment]
And also the status icon+text that's currently on the image needs to be addressed. With JavaScript it would be very easy, but unfortunately using javascript is not possible (see here https://github.com/daattali/oldschool-github-extension/issues/7#issuecomment-649744066)

**Comment by zekefarwell** [comment]
I'd propose letting the tabs on the profile pages look like the old style even though they weren't technically that way before.  At least it's cohesive with the old school github look.  But only if the other issues you've brought up are able to be addressed, and I fully understand and support the reason for avoiding JS.  I'd be happy to put some time into seeing if these issues can be addressed with css, but only if the changes would be welcome.  I opened the issue see if you'd open to modifying those page or if you'd rather they just be left alone.

**Comment by daattali** [comment]
I would also be ok with having the old style repository tabs on the main pages (altough one small issue needs to be worked out - there's a grey underline under the selected tab that should be removed).

I'd be happy to receive a PR like what you propose

**Comment by zekefarwell** [comment]
Cool.  I'll see if I can figure something out in the next few days.
