### ISSUE TITLE
[Req] Bring the contents of the black bar in line with the contents of pages

### ISSUE THREAD

**Issue by karai17** [daattali/oldschool-github-extension#9]
Like with the new left-aligned tabs, the black bar being full-width is pretty much horrible. If you could apply a rule to make the contents of the black bar also centred properly, that would be swell. Pictured below: the page looks passable at 200% scale!

![image](https://user-images.githubusercontent.com/590332/85779649-34139800-b6fa-11ea-9ed2-45f640daa5c4.png)

**Comment by daattali** [comment]
How did the black bar look before the update? I would look into this if the black bar now doesn't match what it was like a week ago

**Comment by karai17** [comment]
I don't think it changed with this update, it's just been horrible since they updated the front page.

**Comment by daattali** [comment]
If it's not something that changed with the new update, I prefer not to touch it. This extension is explicitly for issues that arose this week, not for fixing other UI because then we get into personal taste :)

**Comment by karai17** [comment]
I can understand that. However, I think that this request is in line with one of the major frustrations with this latest update in that the contents of the page shouldn't be aligned to the far edges of the screen. Bringing all of the content within the 1200px centre would be a marked improvement.

**Comment by daattali** [comment]
I really don't want to fiddle with anything that wasn't in the UI before. 

Another example is the file list: in tables with many rows like the file list, it's nice to have alternating rows have slightly different backgrounds. But I did not implement that even though I think it's better because the clear purpose here is to simply try to revert as much as possible the June update, not to impose any subjective design decisions. I agree that a narrower top bar would be better, but I don't want to make any exceptions to the goal of this extension, because from there it will easily snowball into more exceptions.

**Comment by zekefarwell** [comment]
Can confirm that the black bar at the top was full width before the June 23rd.

![EbNkjBTU8AA2JMx](https://user-images.githubusercontent.com/281482/85785767-a040cc80-b6f7-11ea-9f06-756fcd5417f8.png)
Source: https://twitter.com/KevBurnsJr/status/1275475187064909824

However, the black bar was only full width when signed in. When signed out, the black bar matched the content width:
<img width="1424" alt="Screen Shot 2020-06-25 at 3 20 06 PM" src="https://user-images.githubusercontent.com/281482/85786344-2c52f400-b6f8-11ea-841a-0e612856c612.png">

aaand it still matches the content width when signed out in the new design – so bizarre:
<img width="1422" alt="Screen Shot 2020-06-25 at 3 24 02 PM" src="https://user-images.githubusercontent.com/281482/85786426-4096f100-b6f8-11ea-9449-0eddb4fb58d8.png">

I agree it's probably best to stick as close as possible to how things were before 6/23.  Just documenting here for future reference.

**Comment by daattali** [comment]
Thanks for pointing this out. Definitely some questionable decisions by GitHub there, but fixing old problems is out of scope.
